// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Context$Type } from "./Context";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Context"]: Context$Type;
    ["openzeppelin/utils/Context.sol:Context"]: Context$Type;
  }
}
