// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IHyperdriveGovernedRegistry$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IHyperdriveGovernedRegistry",
  "sourceName": "contracts/src/interfaces/IHyperdriveGovernedRegistry.sol",
  "abi": [
    {
      "inputs": [],
      "name": "Unauthorized",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "governance",
          "type": "address"
        }
      ],
      "name": "GovernanceUpdated",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "hyperdrive",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "data",
          "type": "uint256"
        }
      ],
      "name": "HyperdriveInfoUpdated",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_hyperdriveInstance",
          "type": "address"
        }
      ],
      "name": "getHyperdriveInfo",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_hyperdriveInstance",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "_data",
          "type": "uint256"
        }
      ],
      "name": "setHyperdriveInfo",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_governance",
          "type": "address"
        }
      ],
      "name": "updateGovernance",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IHyperdriveGovernedRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IHyperdriveGovernedRegistry$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/src/interfaces/IHyperdriveGovernedRegistry.sol:IHyperdriveGovernedRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IHyperdriveGovernedRegistry$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IHyperdriveGovernedRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IHyperdriveGovernedRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/src/interfaces/IHyperdriveGovernedRegistry.sol:IHyperdriveGovernedRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IHyperdriveGovernedRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IHyperdriveGovernedRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IHyperdriveGovernedRegistry$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/src/interfaces/IHyperdriveGovernedRegistry.sol:IHyperdriveGovernedRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IHyperdriveGovernedRegistry$Type["abi"]>>;
}
