// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHBase$Type } from "./RETHBase";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHBase"]: RETHBase$Type;
    ["contracts/src/instances/reth/RETHBase.sol:RETHBase"]: RETHBase$Type;
  }
}
