// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC4626$Type } from "./IERC4626";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC4626"]: IERC4626$Type;
    ["contracts/src/interfaces/IERC4626.sol:IERC4626"]: IERC4626$Type;
  }
}
