// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHTarget4Deployer$Type } from "./StETHTarget4Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHTarget4Deployer"]: StETHTarget4Deployer$Type;
    ["contracts/src/deployers/steth/StETHTarget4Deployer.sol:StETHTarget4Deployer"]: StETHTarget4Deployer$Type;
  }
}
