// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHHyperdriveDeployerCoordinator$Type } from "./StETHHyperdriveDeployerCoordinator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHHyperdriveDeployerCoordinator"]: StETHHyperdriveDeployerCoordinator$Type;
    ["contracts/src/deployers/steth/StETHHyperdriveDeployerCoordinator.sol:StETHHyperdriveDeployerCoordinator"]: StETHHyperdriveDeployerCoordinator$Type;
  }
}
