// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget0$Type } from "./LsETHTarget0";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget0"]: LsETHTarget0$Type;
    ["contracts/src/instances/lseth/LsETHTarget0.sol:LsETHTarget0"]: LsETHTarget0$Type;
  }
}
