// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20$Type } from "./ERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20"]: ERC20$Type;
    ["solmate/tokens/ERC20.sol:ERC20"]: ERC20$Type;
  }
}
