// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IRocketPoolDAOProtocolSettingsDeposit$Type } from "./IRocketPoolDAOProtocolSettingsDeposit";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRocketPoolDAOProtocolSettingsDeposit"]: IRocketPoolDAOProtocolSettingsDeposit$Type;
    ["contracts/src/interfaces/IRocketPoolDAOProtocolSettingsDeposit.sol:IRocketPoolDAOProtocolSettingsDeposit"]: IRocketPoolDAOProtocolSettingsDeposit$Type;
  }
}
