// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { YieldSpaceMath$Type } from "./YieldSpaceMath";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["YieldSpaceMath"]: YieldSpaceMath$Type;
    ["contracts/src/libraries/YieldSpaceMath.sol:YieldSpaceMath"]: YieldSpaceMath$Type;
  }
}
