// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHTarget3$Type } from "./StETHTarget3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHTarget3"]: StETHTarget3$Type;
    ["contracts/src/instances/steth/StETHTarget3.sol:StETHTarget3"]: StETHTarget3$Type;
  }
}
