// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IRiverV1$Type } from "./IRiverV1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRiverV1"]: IRiverV1$Type;
    ["contracts/src/interfaces/IRiverV1.sol:IRiverV1"]: IRiverV1$Type;
  }
}
