// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHTarget1Deployer$Type } from "./StETHTarget1Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHTarget1Deployer"]: StETHTarget1Deployer$Type;
    ["contracts/src/deployers/steth/StETHTarget1Deployer.sol:StETHTarget1Deployer"]: StETHTarget1Deployer$Type;
  }
}
