// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget2$Type } from "./LsETHTarget2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget2"]: LsETHTarget2$Type;
    ["contracts/src/instances/lseth/LsETHTarget2.sol:LsETHTarget2"]: LsETHTarget2$Type;
  }
}
