// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHTarget0Deployer$Type } from "./EzETHTarget0Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHTarget0Deployer"]: EzETHTarget0Deployer$Type;
    ["contracts/src/deployers/ezeth/EzETHTarget0Deployer.sol:EzETHTarget0Deployer"]: EzETHTarget0Deployer$Type;
  }
}
