// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HyperdriveMath$Type } from "./HyperdriveMath";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HyperdriveMath"]: HyperdriveMath$Type;
    ["contracts/src/libraries/HyperdriveMath.sol:HyperdriveMath"]: HyperdriveMath$Type;
  }
}
