// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHTarget3Deployer$Type } from "./RETHTarget3Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHTarget3Deployer"]: RETHTarget3Deployer$Type;
    ["contracts/src/deployers/reth/RETHTarget3Deployer.sol:RETHTarget3Deployer"]: RETHTarget3Deployer$Type;
  }
}
