version: "3.9"
services:
  ethereum:
    image: ghcr.io/foundry-rs/foundry
    command: |
      'anvil --accounts 30 --block-time 12 --host 0.0.0.0'
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ETH_FROM=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - RPC_URL=http://ethereum:8545
