// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20Forwarder$Type } from "./ERC20Forwarder";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Forwarder"]: ERC20Forwarder$Type;
    ["contracts/src/token/ERC20Forwarder.sol:ERC20Forwarder"]: ERC20Forwarder$Type;
  }
}
