// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IHyperdriveRegistry$Type } from "./IHyperdriveRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IHyperdriveRegistry"]: IHyperdriveRegistry$Type;
    ["contracts/src/interfaces/IHyperdriveRegistry.sol:IHyperdriveRegistry"]: IHyperdriveRegistry$Type;
  }
}
