// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHTarget2$Type } from "./StETHTarget2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHTarget2"]: StETHTarget2$Type;
    ["contracts/src/instances/steth/StETHTarget2.sol:StETHTarget2"]: StETHTarget2$Type;
  }
}
