// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IRestakeManager$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IRestakeManager",
  "sourceName": "contracts/src/interfaces/IRenzo.sol",
  "abi": [
    {
      "inputs": [],
      "name": "calculateTVLs",
      "outputs": [
        {
          "internalType": "uint256[][]",
          "name": "",
          "type": "uint256[][]"
        },
        {
          "internalType": "uint256[]",
          "name": "",
          "type": "uint256[]"
        },
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "depositETH",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "ezETH",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "renzoOracle",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IRestakeManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRestakeManager$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/src/interfaces/IRenzo.sol:IRestakeManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRestakeManager$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IRestakeManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRestakeManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/src/interfaces/IRenzo.sol:IRestakeManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRestakeManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IRestakeManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRestakeManager$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/src/interfaces/IRenzo.sol:IRestakeManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRestakeManager$Type["abi"]>>;
}
