// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20ForwarderFactory$Type } from "./IERC20ForwarderFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20ForwarderFactory"]: IERC20ForwarderFactory$Type;
    ["contracts/src/interfaces/IERC20ForwarderFactory.sol:IERC20ForwarderFactory"]: IERC20ForwarderFactory$Type;
  }
}
