// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeTransferLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SafeTransferLib",
  "sourceName": "solmate/utils/SafeTransferLib.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ba655e795bcf7c3fe1735e908e2fa7b63085a49fa02a3e848073a5d4c90ada6664736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ba655e795bcf7c3fe1735e908e2fa7b63085a49fa02a3e848073a5d4c90ada6664736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function deployContract(
    contractName: "solmate/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "solmate/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "solmate/utils/SafeTransferLib.sol:SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
}
