// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHTarget3Deployer$Type } from "./StETHTarget3Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHTarget3Deployer"]: StETHTarget3Deployer$Type;
    ["contracts/src/deployers/steth/StETHTarget3Deployer.sol:StETHTarget3Deployer"]: StETHTarget3Deployer$Type;
  }
}
