// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget1Deployer$Type } from "./LsETHTarget1Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget1Deployer"]: LsETHTarget1Deployer$Type;
    ["contracts/src/deployers/lseth/LsETHTarget1Deployer.sol:LsETHTarget1Deployer"]: LsETHTarget1Deployer$Type;
  }
}
