// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IHyperdriveRead$Type } from "./IHyperdriveRead";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IHyperdriveRead"]: IHyperdriveRead$Type;
    ["contracts/src/interfaces/IHyperdriveRead.sol:IHyperdriveRead"]: IHyperdriveRead$Type;
  }
}
