// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHHyperdriveCoreDeployer$Type } from "./RETHHyperdriveCoreDeployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHHyperdriveCoreDeployer"]: RETHHyperdriveCoreDeployer$Type;
    ["contracts/src/deployers/reth/RETHHyperdriveCoreDeployer.sol:RETHHyperdriveCoreDeployer"]: RETHHyperdriveCoreDeployer$Type;
  }
}
