// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC4626Target0Deployer$Type } from "./ERC4626Target0Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626Target0Deployer"]: ERC4626Target0Deployer$Type;
    ["contracts/src/deployers/erc4626/ERC4626Target0Deployer.sol:ERC4626Target0Deployer"]: ERC4626Target0Deployer$Type;
  }
}
