// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockSafeCast$Type } from "./MockSafeCast";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockSafeCast"]: MockSafeCast$Type;
    ["contracts/test/MockSafeCast.sol:MockSafeCast"]: MockSafeCast$Type;
  }
}
