// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MockSafeCast$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MockSafeCast",
  "sourceName": "contracts/test/MockSafeCast.sol",
  "abi": [
    {
      "inputs": [],
      "name": "UnsafeCastToInt128",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "UnsafeCastToInt256",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "UnsafeCastToUint112",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "UnsafeCastToUint128",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "x",
          "type": "uint256"
        }
      ],
      "name": "toInt128",
      "outputs": [
        {
          "internalType": "int128",
          "name": "y",
          "type": "int128"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "int256",
          "name": "x",
          "type": "int256"
        }
      ],
      "name": "toInt128",
      "outputs": [
        {
          "internalType": "int128",
          "name": "y",
          "type": "int128"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "x",
          "type": "uint256"
        }
      ],
      "name": "toInt256",
      "outputs": [
        {
          "internalType": "int256",
          "name": "y",
          "type": "int256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "x",
          "type": "uint256"
        }
      ],
      "name": "toUint112",
      "outputs": [
        {
          "internalType": "uint112",
          "name": "y",
          "type": "uint112"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "x",
          "type": "uint256"
        }
      ],
      "name": "toUint128",
      "outputs": [
        {
          "internalType": "uint128",
          "name": "y",
          "type": "uint128"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b50610375806100206000396000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c8063809fdd3311610050578063809fdd33146100c9578063dd2a0316146100fd578063dfbe873b1461011057600080fd5b80630f2422d11461006c57806341d2aa6414610097575b600080fd5b61007f61007a366004610326565b610131565b604051600f9190910b81526020015b60405180910390f35b6100aa6100a5366004610326565b610142565b6040516dffffffffffffffffffffffffffff909116815260200161008e565b6100dc6100d7366004610326565b61014d565b6040516fffffffffffffffffffffffffffffffff909116815260200161008e565b61007f61010b366004610326565b610158565b61012361011e366004610326565b610163565b60405190815260200161008e565b600061013c8261016e565b92915050565b600061013c826101be565b600061013c82610208565b600061013c82610254565b600061013c826102ca565b60006f7fffffffffffffffffffffffffffffff8211156101ba576040517fa5353be500000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b5090565b60006dffffffffffffffffffffffffffff8211156101ba576040517f10d62a2e00000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60006fffffffffffffffffffffffffffffffff8211156101ba576040517f1e15f2a200000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60007fffffffffffffffffffffffffffffffff8000000000000000000000000000000082128061029357506f7fffffffffffffffffffffffffffffff82135b156101ba576040517fa5353be500000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60007f7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8211156101ba576040517f72dd4e0200000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60006020828403121561033857600080fd5b503591905056fea26469706673582212200f98a688102ed5a38c728df86b8d06e5fd37674eb2ee95af5d817292aec2171864736f6c63430008140033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b50600436106100675760003560e01c8063809fdd3311610050578063809fdd33146100c9578063dd2a0316146100fd578063dfbe873b1461011057600080fd5b80630f2422d11461006c57806341d2aa6414610097575b600080fd5b61007f61007a366004610326565b610131565b604051600f9190910b81526020015b60405180910390f35b6100aa6100a5366004610326565b610142565b6040516dffffffffffffffffffffffffffff909116815260200161008e565b6100dc6100d7366004610326565b61014d565b6040516fffffffffffffffffffffffffffffffff909116815260200161008e565b61007f61010b366004610326565b610158565b61012361011e366004610326565b610163565b60405190815260200161008e565b600061013c8261016e565b92915050565b600061013c826101be565b600061013c82610208565b600061013c82610254565b600061013c826102ca565b60006f7fffffffffffffffffffffffffffffff8211156101ba576040517fa5353be500000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b5090565b60006dffffffffffffffffffffffffffff8211156101ba576040517f10d62a2e00000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60006fffffffffffffffffffffffffffffffff8211156101ba576040517f1e15f2a200000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60007fffffffffffffffffffffffffffffffff8000000000000000000000000000000082128061029357506f7fffffffffffffffffffffffffffffff82135b156101ba576040517fa5353be500000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60007f7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8211156101ba576040517f72dd4e0200000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60006020828403121561033857600080fd5b503591905056fea26469706673582212200f98a688102ed5a38c728df86b8d06e5fd37674eb2ee95af5d817292aec2171864736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "MockSafeCast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MockSafeCast$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/test/MockSafeCast.sol:MockSafeCast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MockSafeCast$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "MockSafeCast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MockSafeCast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/test/MockSafeCast.sol:MockSafeCast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MockSafeCast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "MockSafeCast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MockSafeCast$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/test/MockSafeCast.sol:MockSafeCast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MockSafeCast$Type["abi"]>>;
}
