// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC1155Errors$Type } from "./IERC1155Errors";
import { IERC20Errors$Type } from "./IERC20Errors";
import { IERC721Errors$Type } from "./IERC721Errors";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1155Errors"]: IERC1155Errors$Type;
    ["IERC20Errors"]: IERC20Errors$Type;
    ["IERC721Errors"]: IERC721Errors$Type;
    ["openzeppelin/interfaces/draft-IERC6093.sol:IERC1155Errors"]: IERC1155Errors$Type;
    ["openzeppelin/interfaces/draft-IERC6093.sol:IERC20Errors"]: IERC20Errors$Type;
    ["openzeppelin/interfaces/draft-IERC6093.sol:IERC721Errors"]: IERC721Errors$Type;
  }
}
