// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget2Deployer$Type } from "./LsETHTarget2Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget2Deployer"]: LsETHTarget2Deployer$Type;
    ["contracts/src/deployers/lseth/LsETHTarget2Deployer.sol:LsETHTarget2Deployer"]: LsETHTarget2Deployer$Type;
  }
}
