// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockYieldSpaceMath$Type } from "./MockYieldSpaceMath";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockYieldSpaceMath"]: MockYieldSpaceMath$Type;
    ["contracts/test/MockYieldSpaceMath.sol:MockYieldSpaceMath"]: MockYieldSpaceMath$Type;
  }
}
