// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ReentrancyGuard$Type } from "./ReentrancyGuard";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ReentrancyGuard"]: ReentrancyGuard$Type;
    ["openzeppelin/utils/ReentrancyGuard.sol:ReentrancyGuard"]: ReentrancyGuard$Type;
  }
}
