// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IMultiTokenCore$Type } from "./IMultiTokenCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMultiTokenCore"]: IMultiTokenCore$Type;
    ["contracts/src/interfaces/IMultiTokenCore.sol:IMultiTokenCore"]: IMultiTokenCore$Type;
  }
}
