// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IHyperdriveEvents$Type } from "./IHyperdriveEvents";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IHyperdriveEvents"]: IHyperdriveEvents$Type;
    ["contracts/src/interfaces/IHyperdriveEvents.sol:IHyperdriveEvents"]: IHyperdriveEvents$Type;
  }
}
