// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC4626Target3$Type } from "./ERC4626Target3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626Target3"]: ERC4626Target3$Type;
    ["contracts/src/instances/erc4626/ERC4626Target3.sol:ERC4626Target3"]: ERC4626Target3$Type;
  }
}
