// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IRocketDepositPool$Type } from "./IRocketDepositPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRocketDepositPool"]: IRocketDepositPool$Type;
    ["contracts/src/interfaces/IRocketDepositPool.sol:IRocketDepositPool"]: IRocketDepositPool$Type;
  }
}
