// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHTarget2$Type } from "./RETHTarget2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHTarget2"]: RETHTarget2$Type;
    ["contracts/src/instances/reth/RETHTarget2.sol:RETHTarget2"]: RETHTarget2$Type;
  }
}
