// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockEzEthPool$Type } from "./MockEzEthPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockEzEthPool"]: MockEzEthPool$Type;
    ["contracts/test/MockEzEthPool.sol:MockEzEthPool"]: MockEzEthPool$Type;
  }
}
