// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget0Deployer$Type } from "./LsETHTarget0Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget0Deployer"]: LsETHTarget0Deployer$Type;
    ["contracts/src/deployers/lseth/LsETHTarget0Deployer.sol:LsETHTarget0Deployer"]: LsETHTarget0Deployer$Type;
  }
}
