// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHTarget0$Type } from "./EzETHTarget0";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHTarget0"]: EzETHTarget0$Type;
    ["contracts/src/instances/ezeth/EzETHTarget0.sol:EzETHTarget0"]: EzETHTarget0$Type;
  }
}
