// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LPMath$Type } from "./LPMath";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LPMath"]: LPMath$Type;
    ["contracts/src/libraries/LPMath.sol:LPMath"]: LPMath$Type;
  }
}
