// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHHyperdrive$Type } from "./RETHHyperdrive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHHyperdrive"]: RETHHyperdrive$Type;
    ["contracts/src/instances/reth/RETHHyperdrive.sol:RETHHyperdrive"]: RETHHyperdrive$Type;
  }
}
