// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHTarget0$Type } from "./RETHTarget0";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHTarget0"]: RETHTarget0$Type;
    ["contracts/src/instances/reth/RETHTarget0.sol:RETHTarget0"]: RETHTarget0$Type;
  }
}
