// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHTarget1$Type } from "./RETHTarget1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHTarget1"]: RETHTarget1$Type;
    ["contracts/src/instances/reth/RETHTarget1.sol:RETHTarget1"]: RETHTarget1$Type;
  }
}
