// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHTarget1Deployer$Type } from "./EzETHTarget1Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHTarget1Deployer"]: EzETHTarget1Deployer$Type;
    ["contracts/src/deployers/ezeth/EzETHTarget1Deployer.sol:EzETHTarget1Deployer"]: EzETHTarget1Deployer$Type;
  }
}
