// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SafeCast$Type } from "./SafeCast";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SafeCast"]: SafeCast$Type;
    ["contracts/src/libraries/SafeCast.sol:SafeCast"]: SafeCast$Type;
  }
}
