// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HyperdriveBase$Type } from "./HyperdriveBase";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HyperdriveBase"]: HyperdriveBase$Type;
    ["contracts/src/internal/HyperdriveBase.sol:HyperdriveBase"]: HyperdriveBase$Type;
  }
}
