// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHHyperdriveCoreDeployer$Type } from "./EzETHHyperdriveCoreDeployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHHyperdriveCoreDeployer"]: EzETHHyperdriveCoreDeployer$Type;
    ["contracts/src/deployers/ezeth/EzETHHyperdriveCoreDeployer.sol:EzETHHyperdriveCoreDeployer"]: EzETHHyperdriveCoreDeployer$Type;
  }
}
