// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget4$Type } from "./LsETHTarget4";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget4"]: LsETHTarget4$Type;
    ["contracts/src/instances/lseth/LsETHTarget4.sol:LsETHTarget4"]: LsETHTarget4$Type;
  }
}
