// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHTarget2Deployer$Type } from "./RETHTarget2Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHTarget2Deployer"]: RETHTarget2Deployer$Type;
    ["contracts/src/deployers/reth/RETHTarget2Deployer.sol:RETHTarget2Deployer"]: RETHTarget2Deployer$Type;
  }
}
