#:schema ../schema/schema.json

rpc_name = "sepolia"
chainId  = 11155111

[access]
  admin          = "0xd94a3A0BfC798b98a700a785D5C610E8a2d5DBD8"
  governance     = "0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b"
  defaultPausers = ["0x0000000000000000000000000000000000000000"]
  feeCollector   = "0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b"
  sweepCollector = "0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b"
[bounds]
  [bounds.checkpointDuration]
    resolution = { value = 8, unit = "hours" }
    min        = { value = 24, unit = "hours" }
    max        = { value = 24, unit = "hours" }
  [bounds.positionDuration]
    min = { value = 7, unit = "days" }
    max = { value = 30, unit = "days" }
  [bounds.fixedAPR]
    min = { value = 100, unit = "bips" }
    max = { value = 6000, unit = "bips" }
  [bounds.timeStretchAPR]
    min = { value = 100, unit = "bips" }
    max = { value = 6000, unit = "bips" }
[fees]
  [fees.curve]
    min = { value = 10, unit = "bips" }
    max = { value = 100, unit = "bips" }
  [fees.flat]
    min = { value = 1, unit = "bips" }
    max = { value = 10, unit = "bips" }
  [fees.governanceLP]
    min = { value = 1500, unit = "bips" }
    max = { value = 1500, unit = "bips" }
  [fees.governanceZombie]
    min = { value = 300, unit = "bips" }
    max = { value = 300, unit = "bips" }


[[pools]]
  name           = "dai"
  poolType       = "ERC4626"
  deploymentId   = "0xAbbabab"
  salt           = "0x69420"
  contribution   = { value = 100, unit = "ether" }
  fixedAPR       = { value = 5000, unit = "bips" }
  timeStretchAPR = { value = 5000, unit = "bips" }
  [pools.tokens]
    base   = "0x552ceaDf3B47609897279F42D3B3309B604896f3"
    shares = "0xECa45b0391E81c311F1b390808a3BA3214d35eAA"
  [pools.bounds]
    minimumShareReserves     = { value = 10, unit = "bips" }
    minimumTransactionAmount = { value = 1000000, unit = "gwei" }
    positionDuration         = { value = 30, unit = "days" }
    checkpointDuration       = { value = 1, unit = "days" }
    timeStretch              = 0
  [pools.fees]
    curve            = { value = 100, unit = "bips" }
    flat             = { value = 5, unit = "bips" }    # will be multiplied by (position_duration / 365 )
    governanceLP     = { value = 1500, unit = "bips" }
    governanceZombie = { value = 300, unit = "bips" }
  [pools.options]
    asBase    = true
    extraData = "0x00"
