#:schema ../schema/pool-schema.json

rpcName        = "sepolia"
chainId        = 11155111
name           = "RETH"
factory        = "0x82a336e8D545D23967322D0977a3CB5Ba4b22904"
coordinator    = "0x29A073074cB871BEdb5e8E3c10571421fb1d9cF7"
registry       = "0xf66EC2d4B5f85A0735EB1e391384a50f16CF9e56"
deploymentId   = "0xbaff002"
salt           = "0x69420"
contribution   = { value = 1000, unit = "bips" }
fixedAPR       = { value = 5000, unit = "bips" }
timeStretchAPR = { value = 5000, unit = "bips" }
[access]
  admin          = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  governance     = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  feeCollector   = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  sweepCollector = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
[bounds]
  minimumShareReserves     = { value = 10, unit = "bips" }
  minimumTransactionAmount = { value = 1000000, unit = "gwei" }
  positionDuration         = { value = 30, unit = "days" }
  checkpointDuration       = { value = 1, unit = "days" }
  timeStretch              = 0
[fees]
  curve            = { value = 100, unit = "bips" }
  flat             = { value = 5, unit = "bips" }    # will be multiplied by (position_duration / 365 )
  governanceLP     = { value = 1500, unit = "bips" }
  governanceZombie = { value = 300, unit = "bips" }
[options]
  destination = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  asBase      = false
  extraData   = "0x00"
[tokens]
  base   = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
  shares = "0xB546892cA53D47E0ED8cFf2f9b443C748BB8F48e"
