#:schema ../schema/factory-schema.json

rpcName = "sepolia"
chainId = 11155111
[access]
  admin          = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  governance     = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  defaultPausers = ["0x0000000000000000000000000000000000000000"]
  feeCollector   = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  sweepCollector = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
[checkpointDuration]
  resolution = { value = 8, unit = "hours" }
  min        = { value = 24, unit = "hours" }
  max        = { value = 24, unit = "hours" }
[positionDuration]
  min = { value = 7, unit = "days" }
  max = { value = 30, unit = "days" }
[fixedAPR]
  min = { value = 100, unit = "bips" }
  max = { value = 6000, unit = "bips" }
[timeStretchAPR]
  min = { value = 100, unit = "bips" }
  max = { value = 6000, unit = "bips" }
[fees]
  [fees.curve]
    min = { value = 10, unit = "bips" }
    max = { value = 100, unit = "bips" }
  [fees.flat]
    min = { value = 1, unit = "bips" }
    max = { value = 10, unit = "bips" }
  [fees.governanceLP]
    min = { value = 1500, unit = "bips" }
    max = { value = 1500, unit = "bips" }
  [fees.governanceZombie]
    min = { value = 300, unit = "bips" }
    max = { value = 300, unit = "bips" }
