#:schema ../schema/pool-schema.json

rpcName        = "sepolia"
chainId        = 11155111
name           = "RETH"
factory        = "0x338D5634c391ef47FB797417542aa75F4f71A4a6"
coordinator    = "0x4D12e758D43bDdF385CCa096cE60639DeeaD13e4"
registry       = "0xba5156E697d39a03EDA824C19f375383F6b759EA"
deploymentId   = "0x66660A7"
salt           = "0x69420"
contribution   = { value = 1000, unit = "bips" }
fixedAPR       = { value = 300, unit = "bips" }
timeStretchAPR = { value = 300, unit = "bips" }
[access]
  admin          = "0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b"
  governance     = "0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b"
  feeCollector   = "0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b"
  sweepCollector = "0xc187a246Ee5A4Fe4395a8f6C0f9F2AA3A5a06e9b"
[bounds]
  minimumShareReserves     = { value = 10, unit = "bips" }
  minimumTransactionAmount = { value = 1000000, unit = "gwei" }
  positionDuration         = { value = 30, unit = "days" }
  checkpointDuration       = { value = 1, unit = "days" }
  timeStretch              = 0
[fees]
  curve            = { value = 100, unit = "bips" }
  flat             = { value = 5, unit = "bips" }    # will be multiplied by (position_duration / 365 )
  governanceLP     = { value = 1500, unit = "bips" }
  governanceZombie = { value = 300, unit = "bips" }
[options]
  destination = "0x25a6592F1eaA22cD7BFc590A90d56FbB765b1Edc"
  asBase      = false
  extraData   = "0x00"
[tokens]
  base   = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
  shares = "0x8F66811B35D1E249bD731b5eDF8d5A8703afAB27"
