// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockHyperdriveDeployer$Type } from "./MockHyperdriveDeployer";
import { MockHyperdriveTargetDeployer$Type } from "./MockHyperdriveTargetDeployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockHyperdriveDeployer"]: MockHyperdriveDeployer$Type;
    ["MockHyperdriveTargetDeployer"]: MockHyperdriveTargetDeployer$Type;
    ["contracts/test/MockHyperdriveDeployer.sol:MockHyperdriveDeployer"]: MockHyperdriveDeployer$Type;
    ["contracts/test/MockHyperdriveDeployer.sol:MockHyperdriveTargetDeployer"]: MockHyperdriveTargetDeployer$Type;
  }
}
