// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface HyperdriveStorage$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "HyperdriveStorage",
  "sourceName": "contracts/src/internal/HyperdriveStorage.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ReentrancyGuardReentrantCall",
      "type": "error"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "HyperdriveStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HyperdriveStorage$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/src/internal/HyperdriveStorage.sol:HyperdriveStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HyperdriveStorage$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "HyperdriveStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HyperdriveStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/src/internal/HyperdriveStorage.sol:HyperdriveStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HyperdriveStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "HyperdriveStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HyperdriveStorage$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/src/internal/HyperdriveStorage.sol:HyperdriveStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HyperdriveStorage$Type["abi"]>>;
}
