// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IMultiTokenMetadata$Type } from "./IMultiTokenMetadata";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMultiTokenMetadata"]: IMultiTokenMetadata$Type;
    ["contracts/src/interfaces/IMultiTokenMetadata.sol:IMultiTokenMetadata"]: IMultiTokenMetadata$Type;
  }
}
