// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHTarget4$Type } from "./EzETHTarget4";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHTarget4"]: EzETHTarget4$Type;
    ["contracts/src/instances/ezeth/EzETHTarget4.sol:EzETHTarget4"]: EzETHTarget4$Type;
  }
}
