// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MultiRolesAuthority$Type } from "./MultiRolesAuthority";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MultiRolesAuthority"]: MultiRolesAuthority$Type;
    ["solmate/auth/authorities/MultiRolesAuthority.sol:MultiRolesAuthority"]: MultiRolesAuthority$Type;
  }
}
