// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC4626HyperdriveDeployerCoordinator$Type } from "./ERC4626HyperdriveDeployerCoordinator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626HyperdriveDeployerCoordinator"]: ERC4626HyperdriveDeployerCoordinator$Type;
    ["contracts/src/deployers/erc4626/ERC4626HyperdriveDeployerCoordinator.sol:ERC4626HyperdriveDeployerCoordinator"]: ERC4626HyperdriveDeployerCoordinator$Type;
  }
}
