// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20Mintable$Type } from "./ERC20Mintable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Mintable"]: ERC20Mintable$Type;
    ["contracts/test/ERC20Mintable.sol:ERC20Mintable"]: ERC20Mintable$Type;
  }
}
