// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHTarget1$Type } from "./EzETHTarget1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHTarget1"]: EzETHTarget1$Type;
    ["contracts/src/instances/ezeth/EzETHTarget1.sol:EzETHTarget1"]: EzETHTarget1$Type;
  }
}
