// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { FixedPointMath$Type } from "./FixedPointMath";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FixedPointMath"]: FixedPointMath$Type;
    ["contracts/src/libraries/FixedPointMath.sol:FixedPointMath"]: FixedPointMath$Type;
  }
}
