// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface FixedPointMath$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "FixedPointMath",
  "sourceName": "contracts/src/libraries/FixedPointMath.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207c1ae6c13c7c08a85353c984236a8d0090e4bcaf78defbeb0e71d09c803bf64f64736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207c1ae6c13c7c08a85353c984236a8d0090e4bcaf78defbeb0e71d09c803bf64f64736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "FixedPointMath",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FixedPointMath$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/src/libraries/FixedPointMath.sol:FixedPointMath",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FixedPointMath$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "FixedPointMath",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FixedPointMath$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/src/libraries/FixedPointMath.sol:FixedPointMath",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FixedPointMath$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "FixedPointMath",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FixedPointMath$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/src/libraries/FixedPointMath.sol:FixedPointMath",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FixedPointMath$Type["abi"]>>;
}
