// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20ForwarderFactory$Type } from "./ERC20ForwarderFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20ForwarderFactory"]: ERC20ForwarderFactory$Type;
    ["contracts/src/token/ERC20ForwarderFactory.sol:ERC20ForwarderFactory"]: ERC20ForwarderFactory$Type;
  }
}
