// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHBase$Type } from "./EzETHBase";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHBase"]: EzETHBase$Type;
    ["contracts/src/instances/ezeth/EzETHBase.sol:EzETHBase"]: EzETHBase$Type;
  }
}
