// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockLido$Type } from "./MockLido";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockLido"]: MockLido$Type;
    ["contracts/test/MockLido.sol:MockLido"]: MockLido$Type;
  }
}
