[package]
name = "hyperdrive-addresses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ethers = "2.0.8"
serde = { version = "1.0", features = ["derive"] }
