// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHHyperdriveCoreDeployer$Type } from "./LsETHHyperdriveCoreDeployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHHyperdriveCoreDeployer"]: LsETHHyperdriveCoreDeployer$Type;
    ["contracts/src/deployers/lseth/LsETHHyperdriveCoreDeployer.sol:LsETHHyperdriveCoreDeployer"]: LsETHHyperdriveCoreDeployer$Type;
  }
}
