// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IEzETHHyperdriveRead$Type } from "./IEzETHHyperdriveRead";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEzETHHyperdriveRead"]: IEzETHHyperdriveRead$Type;
    ["contracts/src/interfaces/IEzETHHyperdriveRead.sol:IEzETHHyperdriveRead"]: IEzETHHyperdriveRead$Type;
  }
}
