// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IHyperdriveFactory$Type } from "./IHyperdriveFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IHyperdriveFactory"]: IHyperdriveFactory$Type;
    ["contracts/src/interfaces/IHyperdriveFactory.sol:IHyperdriveFactory"]: IHyperdriveFactory$Type;
  }
}
