// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SafeERC20$Type } from "./SafeERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SafeERC20"]: SafeERC20$Type;
    ["openzeppelin/token/ERC20/utils/SafeERC20.sol:SafeERC20"]: SafeERC20$Type;
  }
}
