// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20Metadata$Type } from "./IERC20Metadata";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20Metadata"]: IERC20Metadata$Type;
    ["openzeppelin/token/ERC20/extensions/IERC20Metadata.sol:IERC20Metadata"]: IERC20Metadata$Type;
  }
}
