// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget3Deployer$Type } from "./LsETHTarget3Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget3Deployer"]: LsETHTarget3Deployer$Type;
    ["contracts/src/deployers/lseth/LsETHTarget3Deployer.sol:LsETHTarget3Deployer"]: LsETHTarget3Deployer$Type;
  }
}
