// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockAssetId$Type } from "./MockAssetId";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockAssetId"]: MockAssetId$Type;
    ["contracts/test/MockAssetId.sol:MockAssetId"]: MockAssetId$Type;
  }
}
