// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockRocketPool$Type } from "./MockRocketPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockRocketPool"]: MockRocketPool$Type;
    ["contracts/test/MockRocketPool.sol:MockRocketPool"]: MockRocketPool$Type;
  }
}
