// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHTarget2$Type } from "./EzETHTarget2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHTarget2"]: EzETHTarget2$Type;
    ["contracts/src/instances/ezeth/EzETHTarget2.sol:EzETHTarget2"]: EzETHTarget2$Type;
  }
}
