// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HyperdriveUtils$Type } from "./HyperdriveUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HyperdriveUtils"]: HyperdriveUtils$Type;
    ["test/utils/HyperdriveUtils.sol:HyperdriveUtils"]: HyperdriveUtils$Type;
  }
}
