// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface HyperdriveUtils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "HyperdriveUtils",
  "sourceName": "test/utils/HyperdriveUtils.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207bdeba78266e39c75c8d5e7de3efde08b1dcffcb5557f04bdb408abbe0bfe26264736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207bdeba78266e39c75c8d5e7de3efde08b1dcffcb5557f04bdb408abbe0bfe26264736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "HyperdriveUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HyperdriveUtils$Type["abi"]>>;
  export function deployContract(
    contractName: "test/utils/HyperdriveUtils.sol:HyperdriveUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HyperdriveUtils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "HyperdriveUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HyperdriveUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "test/utils/HyperdriveUtils.sol:HyperdriveUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HyperdriveUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "HyperdriveUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HyperdriveUtils$Type["abi"]>>;
  export function getContractAt(
    contractName: "test/utils/HyperdriveUtils.sol:HyperdriveUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HyperdriveUtils$Type["abi"]>>;
}
