// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HyperdriveDeployerCoordinator$Type } from "./HyperdriveDeployerCoordinator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HyperdriveDeployerCoordinator"]: HyperdriveDeployerCoordinator$Type;
    ["contracts/src/deployers/HyperdriveDeployerCoordinator.sol:HyperdriveDeployerCoordinator"]: HyperdriveDeployerCoordinator$Type;
  }
}
