// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHTarget4$Type } from "./StETHTarget4";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHTarget4"]: StETHTarget4$Type;
    ["contracts/src/instances/steth/StETHTarget4.sol:StETHTarget4"]: StETHTarget4$Type;
  }
}
