// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IHyperdrive$Type } from "./IHyperdrive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IHyperdrive"]: IHyperdrive$Type;
    ["contracts/src/interfaces/IHyperdrive.sol:IHyperdrive"]: IHyperdrive$Type;
  }
}
