// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IRocketNetworkBalances$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IRocketNetworkBalances",
  "sourceName": "contracts/src/interfaces/IRocketNetworkBalances.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_block",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_totalEth",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_stakingEth",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_rethSupply",
          "type": "uint256"
        }
      ],
      "name": "executeUpdateBalances",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getBalancesBlock",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getETHUtilizationRate",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getLatestReportableBlock",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getStakingETHBalance",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getTotalETHBalance",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getTotalRETHSupply",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_block",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_total",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_staking",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_rethSupply",
          "type": "uint256"
        }
      ],
      "name": "submitBalances",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IRocketNetworkBalances",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRocketNetworkBalances$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/src/interfaces/IRocketNetworkBalances.sol:IRocketNetworkBalances",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRocketNetworkBalances$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IRocketNetworkBalances",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRocketNetworkBalances$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/src/interfaces/IRocketNetworkBalances.sol:IRocketNetworkBalances",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRocketNetworkBalances$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IRocketNetworkBalances",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRocketNetworkBalances$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/src/interfaces/IRocketNetworkBalances.sol:IRocketNetworkBalances",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRocketNetworkBalances$Type["abi"]>>;
}
