// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHTarget0Deployer$Type } from "./RETHTarget0Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHTarget0Deployer"]: RETHTarget0Deployer$Type;
    ["contracts/src/deployers/reth/RETHTarget0Deployer.sol:RETHTarget0Deployer"]: RETHTarget0Deployer$Type;
  }
}
