// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LsETHTarget4Deployer$Type } from "./LsETHTarget4Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LsETHTarget4Deployer"]: LsETHTarget4Deployer$Type;
    ["contracts/src/deployers/lseth/LsETHTarget4Deployer.sol:LsETHTarget4Deployer"]: LsETHTarget4Deployer$Type;
  }
}
