// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC4626Base$Type } from "./ERC4626Base";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626Base"]: ERC4626Base$Type;
    ["contracts/src/instances/erc4626/ERC4626Base.sol:ERC4626Base"]: ERC4626Base$Type;
  }
}
