// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Errors$Type } from "./Errors";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Errors"]: Errors$Type;
    ["contracts/src/libraries/Errors.sol:Errors"]: Errors$Type;
  }
}
