[package]

name = "fixed-point-macros"
version = "0.1.0"
edition = "2021"

[lib]

proc-macro = true

[dependencies]

# External dependencies
ethers = "2.0.8"
syn = "2.0"
quote = "1.0"

[dev-dependencies]

# Workspace dependencies
fixed-point = { path = "../fixed-point" }
