// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC4626Target4$Type } from "./ERC4626Target4";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626Target4"]: ERC4626Target4$Type;
    ["contracts/src/instances/erc4626/ERC4626Target4.sol:ERC4626Target4"]: ERC4626Target4$Type;
  }
}
