// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IRETHHyperdriveRead$Type } from "./IRETHHyperdriveRead";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRETHHyperdriveRead"]: IRETHHyperdriveRead$Type;
    ["contracts/src/interfaces/IRETHHyperdriveRead.sol:IRETHHyperdriveRead"]: IRETHHyperdriveRead$Type;
  }
}
