// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HyperdriveLong$Type } from "./HyperdriveLong";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HyperdriveLong"]: HyperdriveLong$Type;
    ["contracts/src/internal/HyperdriveLong.sol:HyperdriveLong"]: HyperdriveLong$Type;
  }
}
