// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RETHTarget3$Type } from "./RETHTarget3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RETHTarget3"]: RETHTarget3$Type;
    ["contracts/src/instances/reth/RETHTarget3.sol:RETHTarget3"]: RETHTarget3$Type;
  }
}
