// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ILido$Type } from "./ILido";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ILido"]: ILido$Type;
    ["contracts/src/interfaces/ILido.sol:ILido"]: ILido$Type;
  }
}
