// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC4626HyperdriveCoreDeployer$Type } from "./ERC4626HyperdriveCoreDeployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626HyperdriveCoreDeployer"]: ERC4626HyperdriveCoreDeployer$Type;
    ["contracts/src/deployers/erc4626/ERC4626HyperdriveCoreDeployer.sol:ERC4626HyperdriveCoreDeployer"]: ERC4626HyperdriveCoreDeployer$Type;
  }
}
