// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { StETHTarget0$Type } from "./StETHTarget0";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StETHTarget0"]: StETHTarget0$Type;
    ["contracts/src/instances/steth/StETHTarget0.sol:StETHTarget0"]: StETHTarget0$Type;
  }
}
