# Template configuration

# Vault naming formats.
name:
  # Capitalized version of the name to be used i.e. for contract names, file
  # names, and comments.
  capitalized: "ExampleName"

  # All upper case name to be used for constants.
  uppercase: "EXAMPLE_NAME"

  # All lower case name to be used for directories.
  lowercase: "example-name"

  # Camel case name to be used i.e. for variables.
  camelcase: "exampleName"

# Configuration parameters for the hyperdrive instance.
contract:
  # If the contract is payable in Ether.  If it is, then logic should be added
  # to accept Ether, and deposit into the vault to obtain vault shares.
  payable: false

  # If the contract can accept base to convert to valut shares on behalf of the
  # user.
  as_base_allowed: true
