// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EzETHTarget3Deployer$Type } from "./EzETHTarget3Deployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EzETHTarget3Deployer"]: EzETHTarget3Deployer$Type;
    ["contracts/src/deployers/ezeth/EzETHTarget3Deployer.sol:EzETHTarget3Deployer"]: EzETHTarget3Deployer$Type;
  }
}
