// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IHyperdriveTargetDeployer$Type } from "./IHyperdriveTargetDeployer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IHyperdriveTargetDeployer"]: IHyperdriveTargetDeployer$Type;
    ["contracts/src/interfaces/IHyperdriveTargetDeployer.sol:IHyperdriveTargetDeployer"]: IHyperdriveTargetDeployer$Type;
  }
}
