// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AssetId$Type } from "./AssetId";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AssetId"]: AssetId$Type;
    ["contracts/src/libraries/AssetId.sol:AssetId"]: AssetId$Type;
  }
}
