name: build and upload hypertypes wheels

on:
  push:
    tags:
      - "v*"

jobs:
  build-wheels-linux:
    name: build linux wheel
    runs-on: ubuntu-latest
    steps:
      - name: checkout hyperdrive
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          token: ${{github.token}}

      - name: set up pip and pypechain
        run: python -m pip install --upgrade pip pypechain

      - name: generate hypertype files
        run: make build

      - name: build hypertypes
        shell: bash
        run: source scripts/build-hypertypes-wheels.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: dist/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build-wheels-linux, build-sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1