name: Publish the devnet image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/devnet

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Add a tag matching the commit hash
            type=sha,format=long,prefix=
            # Add a version tag when a valid semver tag is pushed.
            type=semver,pattern={{version}}
            # Add the edge tag to represent the latest commit to main
            type=raw,value=edge,enable={{is_default_branch}}

      - name: Build and push the Devnet image
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ADMIN=${{ vars.DEVNET_ADMIN }}
            DEPLOYER_PRIVATE_KEY=${{ vars.DEVNET_ADMIN_PRIVATE_KEY }}
            REGISTRY_SALT=${{ vars.REGISTRY_SALT }}
            FACTORY_MIN_CURVE_FEE=0 # 0%
            FACTORY_MIN_FLAT_FEE=0 # 0%
            FACTORY_MIN_GOVERNANCE_LP_FEE=0 # 0%
            FACTORY_MIN_GOVERNANCE_ZOMBIE_FEE=0 # 0%
            FACTORY_MAX_CURVE_FEE=1 # 100%
            FACTORY_MAX_FLAT_FEE=1 # 100%
            FACTORY_MAX_GOVERNANCE_LP_FEE=1 # 100%
            FACTORY_MAX_GOVERNANCE_ZOMBIE_FEE=1 # 100%
            FACTORY_MIN_POSITION_DURATION=1 # 1 Day (in seconds)
