name: Python test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: python test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: This is needed to ensure that hyperdrive-wrappers builds correctly.
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install pip
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest

      - name: Install hyperdrive-math-py
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          python -m pip install crates/hyperdrive-math-py
        
      - name: Run pytest
        run: |
          python -m pytest python/test
