name: Rust Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: rust lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # NOTE: This is needed to ensure that hyperdrive-wrappers builds correctly.
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: lint check
        run: cargo check

      - name: lint clippy
        run: cargo clippy

      - name: fmt check
        run: cargo fmt --check
