name: Solidity Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: solidity test
    runs-on: ubuntu-latest
    env:
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          version: nightly

      - name: test forge
        run: FOUNDRY_FUZZ_RUNS=10000 forge test -vvv
