name: Solidity Test

on:
  push:
  pull_request:
  merge_group:

jobs:
  detect-changes:
    uses: ./.github/workflows/check_diff.yaml
    with:
      pattern: ^contracts/\|^test/\|^lib/\|^foundry\.toml$\|^\.github/workflows/solidity_test\.yml$

  test-core:
    name: solidity test core
    runs-on: ubuntu-latest-16core
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    env:
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          version: nightly

      - name: test
        run: FOUNDRY_FUZZ_RUNS=10000 make test-sol-core

  test-heavy:
    name: solidity test lp withdrawal
    runs-on: ubuntu-latest-16core
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    env:
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          version: nightly

      - name: test
        run: FOUNDRY_FUZZ_RUNS=10000 make test-sol-lp-withdrawal

  test-netting:
    name: solidity test netting
    runs-on: ubuntu-latest-16core
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    env:
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          version: nightly

      - name: test
        run: FOUNDRY_FUZZ_RUNS=10000 make test-sol-netting

  test-zombie:
    name: solidity test zombie
    runs-on: ubuntu-latest-16core
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    env:
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          version: nightly

      - name: test
        run: FOUNDRY_FUZZ_RUNS=1000 make test-sol-zombie
