name: Test Hyperdrivetypes

on:
  push:
  pull_request:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          token: ${{github.token}}

      - name: set up pip and pypechain
        run: >
          python -m pip install --upgrade pip; 
          python -m pip install --upgrade -r python/hyperdrivetypes/prerequisite.txt;

      - name: generate hyperdrivetypes files
        run: make build

      - name: install hyperdrivetypes
        run: python -m pip install python/hyperdrivetypes[all]

      - name: run type checker
        run: python -m pyright python/

      - name: run tests
        run: make test-python
