name: Publish the testnet image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/testnet

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Add a tag matching the commit hash
            type=sha,format=long,prefix=
            # Add a version tag when a valid semver tag is pushed.
            type=semver,pattern={{version}}
            # Add the edge tag to represent the latest commit to main
            type=raw,value=edge,enable={{is_default_branch}}

      - name: Build and push the Testnet image
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ADMIN=${{ vars.TESTNET_ADMIN }}
            IS_COMPETITION_MODE=true
            BASE_TOKEN_NAME=Multi Collateral DAI
            BASE_TOKEN_SYMBOL=DAI
            VAULT_NAME=sDai
            VAULT_SYMBOL=SDAI
            VAULT_STARTING_RATE=50000000000000000 # 5% APR
            LIDO_STARTING_RATE=35000000000000000 # 3.5% APR
            ERC4626_HYPERDRIVE_POSITION_DURATION=31536000 # 1 year in seconds
            ERC4626_HYPERDRIVE_CHECKPOINT_DURATION=86400 # 1 day in seconds
            ERC4626_HYPERDRIVE_FLAT_FEE=50000000000000000 # 5% APR
            STETH_HYPERDRIVE_POSITION_DURATION=31536000 # 1 year in seconds
            STETH_HYPERDRIVE_CHECKPOINT_DURATION=86400 # 1 day in seconds
            STETH_HYPERDRIVE_FLAT_FEE=50000000000000000 # 5% APR
