// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IMockHyperdrive$Type } from "./IMockHyperdrive";
import { MockHyperdrive$Type } from "./MockHyperdrive";
import { MockHyperdriveBase$Type } from "./MockHyperdriveBase";
import { MockHyperdriveTarget0$Type } from "./MockHyperdriveTarget0";
import { MockHyperdriveTarget1$Type } from "./MockHyperdriveTarget1";
import { MockHyperdriveTarget2$Type } from "./MockHyperdriveTarget2";
import { MockHyperdriveTarget3$Type } from "./MockHyperdriveTarget3";
import { MockHyperdriveTarget4$Type } from "./MockHyperdriveTarget4";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMockHyperdrive"]: IMockHyperdrive$Type;
    ["MockHyperdrive"]: MockHyperdrive$Type;
    ["MockHyperdriveBase"]: MockHyperdriveBase$Type;
    ["MockHyperdriveTarget0"]: MockHyperdriveTarget0$Type;
    ["MockHyperdriveTarget1"]: MockHyperdriveTarget1$Type;
    ["MockHyperdriveTarget2"]: MockHyperdriveTarget2$Type;
    ["MockHyperdriveTarget3"]: MockHyperdriveTarget3$Type;
    ["MockHyperdriveTarget4"]: MockHyperdriveTarget4$Type;
    ["contracts/test/MockHyperdrive.sol:IMockHyperdrive"]: IMockHyperdrive$Type;
    ["contracts/test/MockHyperdrive.sol:MockHyperdrive"]: MockHyperdrive$Type;
    ["contracts/test/MockHyperdrive.sol:MockHyperdriveBase"]: MockHyperdriveBase$Type;
    ["contracts/test/MockHyperdrive.sol:MockHyperdriveTarget0"]: MockHyperdriveTarget0$Type;
    ["contracts/test/MockHyperdrive.sol:MockHyperdriveTarget1"]: MockHyperdriveTarget1$Type;
    ["contracts/test/MockHyperdrive.sol:MockHyperdriveTarget2"]: MockHyperdriveTarget2$Type;
    ["contracts/test/MockHyperdrive.sol:MockHyperdriveTarget3"]: MockHyperdriveTarget3$Type;
    ["contracts/test/MockHyperdrive.sol:MockHyperdriveTarget4"]: MockHyperdriveTarget4$Type;
  }
}
