// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HyperdriveCheckpoint$Type } from "./HyperdriveCheckpoint";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HyperdriveCheckpoint"]: HyperdriveCheckpoint$Type;
    ["contracts/src/internal/HyperdriveCheckpoint.sol:HyperdriveCheckpoint"]: HyperdriveCheckpoint$Type;
  }
}
